/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AguardandoAprovacaoRouteImport } from './routes/aguardando-aprovacao'
import { Route as AlterarSenhaObrigatoriaRouteImport } from './routes/alterar-senha-obrigatoria'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CadastroRejeitadoRouteImport } from './routes/cadastro-rejeitado'
import { Route as ContaBanidaRouteImport } from './routes/conta-banida'
import { Route as ContaBloqueadaRouteImport } from './routes/conta-bloqueada'
import { Route as ContaExcluidaRouteImport } from './routes/conta-excluida'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedRecuperacaoRouteImport } from './routes/_authenticated/recuperacao'
import { Route as AuthenticatedScriptComercialRouteImport } from './routes/_authenticated/script-comercial'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAtividadeRouteImport } from './routes/admin.atividade'
import { Route as AdminMensagensRouteImport } from './routes/admin.mensagens'
import { Route as AuthenticatedConfiguracoesEquipeRouteImport } from './routes/_authenticated/configuracoes_.equipe'
import { Route as AuthenticatedGarimposIndexRouteImport } from './routes/_authenticated/garimpos.index'
import { Route as AuthenticatedGarimposIdRouteImport } from './routes/_authenticated/garimpos.$id'
import { Route as AuthenticatedGarimposImportarRouteImport } from './routes/_authenticated/garimpos.importar'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AdminUsuariosIndexRouteImport } from './routes/admin.usuarios.index'
import { Route as AdminUsuariosIdRouteImport } from './routes/admin.usuarios.$id'
import { Route as AuthenticatedGarimposLotesIdRouteImport } from './routes/_authenticated/garimpos.lotes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AguardandoAprovacaoRoute = AguardandoAprovacaoRouteImport.update({
  id: '/aguardando-aprovacao',
  path: '/aguardando-aprovacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AlterarSenhaObrigatoriaRoute = AlterarSenhaObrigatoriaRouteImport.update({
  id: '/alterar-senha-obrigatoria',
  path: '/alterar-senha-obrigatoria',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRejeitadoRoute = CadastroRejeitadoRouteImport.update({
  id: '/cadastro-rejeitado',
  path: '/cadastro-rejeitado',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaBanidaRoute = ContaBanidaRouteImport.update({
  id: '/conta-banida',
  path: '/conta-banida',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaBloqueadaRoute = ContaBloqueadaRouteImport.update({
  id: '/conta-bloqueada',
  path: '/conta-bloqueada',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaExcluidaRoute = ContaExcluidaRouteImport.update({
  id: '/conta-excluida',
  path: '/conta-excluida',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecuperacaoRoute =
  AuthenticatedRecuperacaoRouteImport.update({
    id: '/recuperacao',
    path: '/recuperacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScriptComercialRoute =
  AuthenticatedScriptComercialRouteImport.update({
    id: '/script-comercial',
    path: '/script-comercial',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAtividadeRoute = AdminAtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMensagensRoute = AdminMensagensRouteImport.update({
  id: '/mensagens',
  path: '/mensagens',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedConfiguracoesEquipeRoute =
  AuthenticatedConfiguracoesEquipeRouteImport.update({
    id: '/configuracoes_/equipe',
    path: '/configuracoes/equipe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGarimposIndexRoute =
  AuthenticatedGarimposIndexRouteImport.update({
    id: '/garimpos/',
    path: '/garimpos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGarimposIdRoute = AuthenticatedGarimposIdRouteImport.update({
  id: '/garimpos/$id',
  path: '/garimpos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGarimposImportarRoute =
  AuthenticatedGarimposImportarRouteImport.update({
    id: '/garimpos/importar',
    path: '/garimpos/importar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AdminUsuariosIndexRoute = AdminUsuariosIndexRouteImport.update({
  id: '/usuarios/',
  path: '/usuarios/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosIdRoute = AdminUsuariosIdRouteImport.update({
  id: '/usuarios/$id',
  path: '/usuarios/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedGarimposLotesIdRoute =
  AuthenticatedGarimposLotesIdRouteImport.update({
    id: '/garimpos/lotes/$id',
    path: '/garimpos/lotes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/alterar-senha-obrigatoria': typeof AlterarSenhaObrigatoriaRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-rejeitado': typeof CadastroRejeitadoRoute
  '/conta-banida': typeof ContaBanidaRoute
  '/conta-bloqueada': typeof ContaBloqueadaRoute
  '/conta-excluida': typeof ContaExcluidaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/script-comercial': typeof AuthenticatedScriptComercialRoute
  '/admin/atividade': typeof AdminAtividadeRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/': typeof AdminIndexRoute
  '/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/garimpos/$id': typeof AuthenticatedGarimposIdRoute
  '/garimpos/importar': typeof AuthenticatedGarimposImportarRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/garimpos/': typeof AuthenticatedGarimposIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/garimpos/lotes/$id': typeof AuthenticatedGarimposLotesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/alterar-senha-obrigatoria': typeof AlterarSenhaObrigatoriaRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-rejeitado': typeof CadastroRejeitadoRoute
  '/conta-banida': typeof ContaBanidaRoute
  '/conta-bloqueada': typeof ContaBloqueadaRoute
  '/conta-excluida': typeof ContaExcluidaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/script-comercial': typeof AuthenticatedScriptComercialRoute
  '/admin/atividade': typeof AdminAtividadeRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin': typeof AdminIndexRoute
  '/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/garimpos/$id': typeof AuthenticatedGarimposIdRoute
  '/garimpos/importar': typeof AuthenticatedGarimposImportarRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/garimpos': typeof AuthenticatedGarimposIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/admin/usuarios': typeof AdminUsuariosIndexRoute
  '/garimpos/lotes/$id': typeof AuthenticatedGarimposLotesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/aguardando-aprovacao': typeof AguardandoAprovacaoRoute
  '/alterar-senha-obrigatoria': typeof AlterarSenhaObrigatoriaRoute
  '/cadastro': typeof CadastroRoute
  '/cadastro-rejeitado': typeof CadastroRejeitadoRoute
  '/conta-banida': typeof ContaBanidaRoute
  '/conta-bloqueada': typeof ContaBloqueadaRoute
  '/conta-excluida': typeof ContaExcluidaRoute
  '/login': typeof LoginRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/_authenticated/script-comercial': typeof AuthenticatedScriptComercialRoute
  '/admin/atividade': typeof AdminAtividadeRoute
  '/admin/mensagens': typeof AdminMensagensRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/configuracoes_/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/_authenticated/garimpos/$id': typeof AuthenticatedGarimposIdRoute
  '/_authenticated/garimpos/importar': typeof AuthenticatedGarimposImportarRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/admin/usuarios/$id': typeof AdminUsuariosIdRoute
  '/_authenticated/garimpos/': typeof AuthenticatedGarimposIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/admin/usuarios/': typeof AdminUsuariosIndexRoute
  '/_authenticated/garimpos/lotes/$id': typeof AuthenticatedGarimposLotesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/aguardando-aprovacao'
    | '/alterar-senha-obrigatoria'
    | '/cadastro'
    | '/cadastro-rejeitado'
    | '/conta-banida'
    | '/conta-bloqueada'
    | '/conta-excluida'
    | '/login'
    | '/redefinir-senha'
    | '/agenda'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/pipeline'
    | '/producao'
    | '/recuperacao'
    | '/script-comercial'
    | '/admin/atividade'
    | '/admin/mensagens'
    | '/admin/'
    | '/configuracoes/equipe'
    | '/garimpos/$id'
    | '/garimpos/importar'
    | '/leads/$id'
    | '/admin/usuarios/$id'
    | '/garimpos/'
    | '/leads/'
    | '/admin/usuarios/'
    | '/garimpos/lotes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aguardando-aprovacao'
    | '/alterar-senha-obrigatoria'
    | '/cadastro'
    | '/cadastro-rejeitado'
    | '/conta-banida'
    | '/conta-bloqueada'
    | '/conta-excluida'
    | '/login'
    | '/redefinir-senha'
    | '/agenda'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/pipeline'
    | '/producao'
    | '/recuperacao'
    | '/script-comercial'
    | '/admin/atividade'
    | '/admin/mensagens'
    | '/admin'
    | '/configuracoes/equipe'
    | '/garimpos/$id'
    | '/garimpos/importar'
    | '/leads/$id'
    | '/admin/usuarios/$id'
    | '/garimpos'
    | '/leads'
    | '/admin/usuarios'
    | '/garimpos/lotes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/aguardando-aprovacao'
    | '/alterar-senha-obrigatoria'
    | '/cadastro'
    | '/cadastro-rejeitado'
    | '/conta-banida'
    | '/conta-bloqueada'
    | '/conta-excluida'
    | '/login'
    | '/redefinir-senha'
    | '/_authenticated/agenda'
    | '/_authenticated/arquivos'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/pipeline'
    | '/_authenticated/producao'
    | '/_authenticated/recuperacao'
    | '/_authenticated/script-comercial'
    | '/admin/atividade'
    | '/admin/mensagens'
    | '/admin/'
    | '/_authenticated/configuracoes_/equipe'
    | '/_authenticated/garimpos/$id'
    | '/_authenticated/garimpos/importar'
    | '/_authenticated/leads/$id'
    | '/admin/usuarios/$id'
    | '/_authenticated/garimpos/'
    | '/_authenticated/leads/'
    | '/admin/usuarios/'
    | '/_authenticated/garimpos/lotes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AguardandoAprovacaoRoute: typeof AguardandoAprovacaoRoute
  AlterarSenhaObrigatoriaRoute: typeof AlterarSenhaObrigatoriaRoute
  CadastroRoute: typeof CadastroRoute
  CadastroRejeitadoRoute: typeof CadastroRejeitadoRoute
  ContaBanidaRoute: typeof ContaBanidaRoute
  ContaBloqueadaRoute: typeof ContaBloqueadaRoute
  ContaExcluidaRoute: typeof ContaExcluidaRoute
  LoginRoute: typeof LoginRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aguardando-aprovacao': {
      id: '/aguardando-aprovacao'
      path: '/aguardando-aprovacao'
      fullPath: '/aguardando-aprovacao'
      preLoaderRoute: typeof AguardandoAprovacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alterar-senha-obrigatoria': {
      id: '/alterar-senha-obrigatoria'
      path: '/alterar-senha-obrigatoria'
      fullPath: '/alterar-senha-obrigatoria'
      preLoaderRoute: typeof AlterarSenhaObrigatoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro-rejeitado': {
      id: '/cadastro-rejeitado'
      path: '/cadastro-rejeitado'
      fullPath: '/cadastro-rejeitado'
      preLoaderRoute: typeof CadastroRejeitadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-banida': {
      id: '/conta-banida'
      path: '/conta-banida'
      fullPath: '/conta-banida'
      preLoaderRoute: typeof ContaBanidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-bloqueada': {
      id: '/conta-bloqueada'
      path: '/conta-bloqueada'
      fullPath: '/conta-bloqueada'
      preLoaderRoute: typeof ContaBloqueadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta-excluida': {
      id: '/conta-excluida'
      path: '/conta-excluida'
      fullPath: '/conta-excluida'
      preLoaderRoute: typeof ContaExcluidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recuperacao': {
      id: '/_authenticated/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof AuthenticatedRecuperacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/script-comercial': {
      id: '/_authenticated/script-comercial'
      path: '/script-comercial'
      fullPath: '/script-comercial'
      preLoaderRoute: typeof AuthenticatedScriptComercialRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/atividade': {
      id: '/admin/atividade'
      path: '/atividade'
      fullPath: '/admin/atividade'
      preLoaderRoute: typeof AdminAtividadeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mensagens': {
      id: '/admin/mensagens'
      path: '/mensagens'
      fullPath: '/admin/mensagens'
      preLoaderRoute: typeof AdminMensagensRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/configuracoes_/equipe': {
      id: '/_authenticated/configuracoes_/equipe'
      path: '/configuracoes/equipe'
      fullPath: '/configuracoes/equipe'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/': {
      id: '/_authenticated/garimpos/'
      path: '/garimpos'
      fullPath: '/garimpos/'
      preLoaderRoute: typeof AuthenticatedGarimposIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/$id': {
      id: '/_authenticated/garimpos/$id'
      path: '/garimpos/$id'
      fullPath: '/garimpos/$id'
      preLoaderRoute: typeof AuthenticatedGarimposIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/importar': {
      id: '/_authenticated/garimpos/importar'
      path: '/garimpos/importar'
      fullPath: '/garimpos/importar'
      preLoaderRoute: typeof AuthenticatedGarimposImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/admin/usuarios/': {
      id: '/admin/usuarios/'
      path: '/usuarios'
      fullPath: '/admin/usuarios/'
      preLoaderRoute: typeof AdminUsuariosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios/$id': {
      id: '/admin/usuarios/$id'
      path: '/usuarios/$id'
      fullPath: '/admin/usuarios/$id'
      preLoaderRoute: typeof AdminUsuariosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/garimpos/lotes/$id': {
      id: '/_authenticated/garimpos/lotes/$id'
      path: '/garimpos/lotes/$id'
      fullPath: '/garimpos/lotes/$id'
      preLoaderRoute: typeof AuthenticatedGarimposLotesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedRecuperacaoRoute: typeof AuthenticatedRecuperacaoRoute
  AuthenticatedScriptComercialRoute: typeof AuthenticatedScriptComercialRoute
  AuthenticatedConfiguracoesEquipeRoute: typeof AuthenticatedConfiguracoesEquipeRoute
  AuthenticatedGarimposIdRoute: typeof AuthenticatedGarimposIdRoute
  AuthenticatedGarimposImportarRoute: typeof AuthenticatedGarimposImportarRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedGarimposIndexRoute: typeof AuthenticatedGarimposIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedGarimposLotesIdRoute: typeof AuthenticatedGarimposLotesIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedRecuperacaoRoute: AuthenticatedRecuperacaoRoute,
  AuthenticatedScriptComercialRoute: AuthenticatedScriptComercialRoute,
  AuthenticatedConfiguracoesEquipeRoute: AuthenticatedConfiguracoesEquipeRoute,
  AuthenticatedGarimposIdRoute: AuthenticatedGarimposIdRoute,
  AuthenticatedGarimposImportarRoute: AuthenticatedGarimposImportarRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedGarimposIndexRoute: AuthenticatedGarimposIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedGarimposLotesIdRoute: AuthenticatedGarimposLotesIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminAtividadeRoute: typeof AdminAtividadeRoute
  AdminMensagensRoute: typeof AdminMensagensRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminUsuariosIdRoute: typeof AdminUsuariosIdRoute
  AdminUsuariosIndexRoute: typeof AdminUsuariosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAtividadeRoute: AdminAtividadeRoute,
  AdminMensagensRoute: AdminMensagensRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminUsuariosIdRoute: AdminUsuariosIdRoute,
  AdminUsuariosIndexRoute: AdminUsuariosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AguardandoAprovacaoRoute: AguardandoAprovacaoRoute,
  AlterarSenhaObrigatoriaRoute: AlterarSenhaObrigatoriaRoute,
  CadastroRoute: CadastroRoute,
  CadastroRejeitadoRoute: CadastroRejeitadoRoute,
  ContaBanidaRoute: ContaBanidaRoute,
  ContaBloqueadaRoute: ContaBloqueadaRoute,
  ContaExcluidaRoute: ContaExcluidaRoute,
  LoginRoute: LoginRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
