/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedArquivosRouteImport } from './routes/_authenticated/arquivos'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedRecuperacaoRouteImport } from './routes/_authenticated/recuperacao'
import { Route as AuthenticatedConfiguracoesEquipeRouteImport } from './routes/_authenticated/configuracoes_.equipe'
import { Route as AuthenticatedGarimposIndexRouteImport } from './routes/_authenticated/garimpos.index'
import { Route as AuthenticatedGarimposIdRouteImport } from './routes/_authenticated/garimpos.$id'
import { Route as AuthenticatedGarimposImportarRouteImport } from './routes/_authenticated/garimpos.importar'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsIdRouteImport } from './routes/_authenticated/leads.$id'
import { Route as AuthenticatedGarimposLotesIdRouteImport } from './routes/_authenticated/garimpos.lotes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedArquivosRoute = AuthenticatedArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecuperacaoRoute =
  AuthenticatedRecuperacaoRouteImport.update({
    id: '/recuperacao',
    path: '/recuperacao',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedConfiguracoesEquipeRoute =
  AuthenticatedConfiguracoesEquipeRouteImport.update({
    id: '/configuracoes_/equipe',
    path: '/configuracoes/equipe',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGarimposIndexRoute =
  AuthenticatedGarimposIndexRouteImport.update({
    id: '/garimpos/',
    path: '/garimpos/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGarimposIdRoute = AuthenticatedGarimposIdRouteImport.update({
  id: '/garimpos/$id',
  path: '/garimpos/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGarimposImportarRoute =
  AuthenticatedGarimposImportarRouteImport.update({
    id: '/garimpos/importar',
    path: '/garimpos/importar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLeadsIdRoute = AuthenticatedLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGarimposLotesIdRoute =
  AuthenticatedGarimposLotesIdRouteImport.update({
    id: '/garimpos/lotes/$id',
    path: '/garimpos/lotes/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/garimpos/$id': typeof AuthenticatedGarimposIdRoute
  '/garimpos/importar': typeof AuthenticatedGarimposImportarRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/garimpos/': typeof AuthenticatedGarimposIndexRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/garimpos/lotes/$id': typeof AuthenticatedGarimposLotesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/arquivos': typeof AuthenticatedArquivosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/configuracoes/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/garimpos/$id': typeof AuthenticatedGarimposIdRoute
  '/garimpos/importar': typeof AuthenticatedGarimposImportarRoute
  '/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/garimpos': typeof AuthenticatedGarimposIndexRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/garimpos/lotes/$id': typeof AuthenticatedGarimposLotesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/arquivos': typeof AuthenticatedArquivosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/recuperacao': typeof AuthenticatedRecuperacaoRoute
  '/_authenticated/configuracoes_/equipe': typeof AuthenticatedConfiguracoesEquipeRoute
  '/_authenticated/garimpos/$id': typeof AuthenticatedGarimposIdRoute
  '/_authenticated/garimpos/importar': typeof AuthenticatedGarimposImportarRoute
  '/_authenticated/leads/$id': typeof AuthenticatedLeadsIdRoute
  '/_authenticated/garimpos/': typeof AuthenticatedGarimposIndexRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/garimpos/lotes/$id': typeof AuthenticatedGarimposLotesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agenda'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/pipeline'
    | '/producao'
    | '/recuperacao'
    | '/configuracoes/equipe'
    | '/garimpos/$id'
    | '/garimpos/importar'
    | '/leads/$id'
    | '/garimpos/'
    | '/leads/'
    | '/garimpos/lotes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agenda'
    | '/arquivos'
    | '/clientes'
    | '/configuracoes'
    | '/dashboard'
    | '/financeiro'
    | '/pipeline'
    | '/producao'
    | '/recuperacao'
    | '/configuracoes/equipe'
    | '/garimpos/$id'
    | '/garimpos/importar'
    | '/leads/$id'
    | '/garimpos'
    | '/leads'
    | '/garimpos/lotes/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/agenda'
    | '/_authenticated/arquivos'
    | '/_authenticated/clientes'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/pipeline'
    | '/_authenticated/producao'
    | '/_authenticated/recuperacao'
    | '/_authenticated/configuracoes_/equipe'
    | '/_authenticated/garimpos/$id'
    | '/_authenticated/garimpos/importar'
    | '/_authenticated/leads/$id'
    | '/_authenticated/garimpos/'
    | '/_authenticated/leads/'
    | '/_authenticated/garimpos/lotes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/arquivos': {
      id: '/_authenticated/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof AuthenticatedArquivosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recuperacao': {
      id: '/_authenticated/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof AuthenticatedRecuperacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/configuracoes_/equipe': {
      id: '/_authenticated/configuracoes_/equipe'
      path: '/configuracoes/equipe'
      fullPath: '/configuracoes/equipe'
      preLoaderRoute: typeof AuthenticatedConfiguracoesEquipeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/': {
      id: '/_authenticated/garimpos/'
      path: '/garimpos'
      fullPath: '/garimpos/'
      preLoaderRoute: typeof AuthenticatedGarimposIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/$id': {
      id: '/_authenticated/garimpos/$id'
      path: '/garimpos/$id'
      fullPath: '/garimpos/$id'
      preLoaderRoute: typeof AuthenticatedGarimposIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/importar': {
      id: '/_authenticated/garimpos/importar'
      path: '/garimpos/importar'
      fullPath: '/garimpos/importar'
      preLoaderRoute: typeof AuthenticatedGarimposImportarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/leads'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/leads/$id': {
      id: '/_authenticated/leads/$id'
      path: '/leads/$id'
      fullPath: '/leads/$id'
      preLoaderRoute: typeof AuthenticatedLeadsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/garimpos/lotes/$id': {
      id: '/_authenticated/garimpos/lotes/$id'
      path: '/garimpos/lotes/$id'
      fullPath: '/garimpos/lotes/$id'
      preLoaderRoute: typeof AuthenticatedGarimposLotesIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedArquivosRoute: typeof AuthenticatedArquivosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedRecuperacaoRoute: typeof AuthenticatedRecuperacaoRoute
  AuthenticatedConfiguracoesEquipeRoute: typeof AuthenticatedConfiguracoesEquipeRoute
  AuthenticatedGarimposIdRoute: typeof AuthenticatedGarimposIdRoute
  AuthenticatedGarimposImportarRoute: typeof AuthenticatedGarimposImportarRoute
  AuthenticatedLeadsIdRoute: typeof AuthenticatedLeadsIdRoute
  AuthenticatedGarimposIndexRoute: typeof AuthenticatedGarimposIndexRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
  AuthenticatedGarimposLotesIdRoute: typeof AuthenticatedGarimposLotesIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedArquivosRoute: AuthenticatedArquivosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedRecuperacaoRoute: AuthenticatedRecuperacaoRoute,
  AuthenticatedConfiguracoesEquipeRoute: AuthenticatedConfiguracoesEquipeRoute,
  AuthenticatedGarimposIdRoute: AuthenticatedGarimposIdRoute,
  AuthenticatedGarimposImportarRoute: AuthenticatedGarimposImportarRoute,
  AuthenticatedLeadsIdRoute: AuthenticatedLeadsIdRoute,
  AuthenticatedGarimposIndexRoute: AuthenticatedGarimposIndexRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
  AuthenticatedGarimposLotesIdRoute: AuthenticatedGarimposLotesIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
